import './globals.css'

export const metadata = {
  title: 'The Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1 className='text-5xl text-red-500'>Pruebaaaa</h1>
        {children}
      </body>
    </html>
  )
}
